### ISSUE TITLE
Running dkenv without any arguments should display the help text

### ISSUE THREAD

**Issue by spkane** [newrelic/dkenv#1]
Instead of:

$ dkenv
version has value
apiVersion has value
flag: help requested

We should get:

$ dkenv
Usage of dkenv:
  -apiVersion="": API Version
  -list=false: Docker Version
  -version="": Docker Version

**Comment by mikkergimenez** [comment]
This has been fixed by the latest commit:

https://github.com/newrelic/dkenv/commit/32172c099c97d9b0245e9536694cab598d26a020
