### ISSUE TITLE
dkenv can't download 1.11.0

### ISSUE THREAD

**Issue by idleyoungman** [newrelic/dkenv#15]
The path we're using for downloading the docker binary doesn't work for 1.11.0:
https://github.com/newrelic/dkenv/blob/master/lib/downloader.go#L78

Also the introduction of additional binaries in the 1.11.0 release may require a new strategy for dkenv.

**Comment by toffer** [comment]
Some additional info:

Starting with version 1.11.0, the binaries are distributed as tarballs and the download URLs now end in `.tgz` like this:

```
https://get.docker.com/builds/Darwin/x86_64/docker-1.11.0.tgz
```

See https://docs.docker.com/engine/installation/binaries/

So, for versions > 1.11.0, there will need to be a slightly different download process: 
1. download tarball (to `/tmp`?)
2. untar it
3. copy the docker client binary to `DkenvDir`
4. clean up!

**Comment by idleyoungman** [comment]
Closing this due to dkenv's retirement per https://github.com/newrelic/dkenv/pull/18
