### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Integralist** [newrelic/dkenv#17]
Hello 👋 

I was unable to build the binary based off the given instructions:

> Note: I'm using `go version go1.12.7 darwin/amd64`

```
$ GOPATH=/Users/integralist/go && $GOPATH/bin/godep go build -o dkenv main.go

godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.

godep: WARNING: Go version (go1.12) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists

main.go:4:2: cannot find package "github.com/newrelic/dkenv/cli" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/newrelic/dkenv/cli (from $GOROOT)
        /Users/integralist/go/src/github.com/newrelic/dkenv/Godeps/_workspace/src/github.com/newrelic/dkenv/cli (from $GOPATH)
main.go:5:2: cannot find package "github.com/newrelic/dkenv/lib" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/newrelic/dkenv/lib (from $GOROOT)
        /Users/integralist/go/src/github.com/newrelic/dkenv/Godeps/_workspace/src/github.com/newrelic/dkenv/lib (from $GOPATH)

godep: go exit status 1
```

To get it to build I wanted to try symlinking the directories `/newrelic/dkenv/lib` and `/newrelic/dkenv/cli` into the nested `Godeps/_workspace/...` directory as the error suggests they were missing from there, but I couldn’t do that for whatever reason (I imagine because of the crazy inception of it all). 

So I had to copy those directories to my desktop first then symlink to there instead.

I'm positive I've well and truly done the wrong things to get it to build, but that's what worked for me 🤷‍♂ 

Thought I'd raise an issue so the documentation/README can be updated to hopefully reflect a better approach for more modern Go versions.

Thanks!

**Comment by idleyoungman** [comment]
Hi @Integralist! Sorry to say this project has been long abandoned. I'll take this issue as a TODO to update the README to reflect this and encourage folks to look at https://github.com/howtowhale/dvm or similar.

**Comment by idleyoungman** [comment]
Closing this due to dkenv's retirement per https://github.com/newrelic/dkenv/pull/18
