### ISSUE TITLE
binary dkenv

### ISSUE THREAD

**Issue by fentas** [newrelic/dkenv#5]
Hi there,
I downloaded bin for linux but getting not the results I expect.
Always getting `2015/08/19 11:43:49 user: Current not implemented on linux/amd64`.

 I just read that using `gccgo` to compile would solve the issue.

**Comment by dselans** [comment]
Sorry for the late response - this will be fixed in the upcoming release.

**Comment by dselans** [comment]
This release should fix the issue(s) you were experiencing: https://github.com/newrelic/dkenv/releases/tag/v1.1.0
